### ISSUE TITLE
The metadata specified with -m are treated in a case-sensitive manner

### ISSUE THREAD

**Issue by loverdos** [grnet/snf-image-creator#39]
This is initially opened in [snf-vmcatcher](https://github.com/grnet/snf-vmcatcher) as https://github.com/grnet/snf-vmcatcher/issues/1

I am opening this one as well for cross-checking/investigating.

For the record, `snf-vmcatcher` sends `-m osfamily=Linux` in the particular case mentioned.

**Comment by skalkoto** [comment]
the problem is that snf-image-creator treats the metadata specified through -m in a case-sensitive way. If you specify ``-m osfamily=something`` the program will add this to the metadata list but it will also define its own ``OSFAMILY`` metadata. When registering the image, both metadata will be send to the server.

**Comment by loverdos** [comment]
I am changing `snf-vmcatcher` to use uppercase, at least to be in the safe side from its POV.
